// src/components/Navbar.vue
<template>
  <nav :class="['fixed top-0 left-0 right-0 z-50 transition-all duration-500', scrolled ? 'shadow-lg bg-white/95' : 'bg-transparent']">
    <div class="max-w-7xl mx-auto px-6 lg:px-8">
      <div class="flex items-center justify-between h-16 lg:h-20">
        <!-- Logo -->
        <a href="#" class="flex items-center gap-2">
          <div class="w-9 h-9 rounded-xl bg-gradient-to-br from-teal-500 to-green-500 flex items-center justify-center">
            <span class="text-white font-bold">S</span>
          </div>
          <span class="text-xl font-bold">Safe<span class="text-teal-500">Nest</span></span>
        </a>

        <!-- Desktop links -->
        <div class="hidden md:flex items-center gap-8">
          <a v-for="link in navLinks" :key="link.href" :href="link.href" class="text-sm font-medium hover:text-teal-500 transition-colors">
            {{ link.label }}
          </a>
          <a href="#pricing" class="px-5 py-2.5 rounded-full bg-navy-900 text-white text-sm font-semibold hover:shadow-lg transition-all">
            Commencer
          </a>
        </div>

        <!-- Mobile toggle -->
        <button @click="isOpen = !isOpen" class="md:hidden p-2">
          {{ isOpen ? '✕' : '☰' }}
        </button>
      </div>

      <!-- Mobile menu -->
      <div v-if="isOpen" class="md:hidden pb-4">
        <a v-for="link in navLinks" :key="link.href" :href="link.href" class="block px-4 py-2 hover:bg-gray-100">
          {{ link.label }}
        </a>
      </div>
    </div>
  </nav>
</template>

<script setup>
import { ref, onMounted, onUnmounted } from 'vue'

const isOpen = ref(false)
const scrolled = ref(false)

const navLinks = [
  { label: 'Solution', href: '#solution' },
  { label: 'Fonctionnalités', href: '#features' },
  { label: 'Pourquoi nous', href: '#values' },
  { label: 'Tarifs', href: '#pricing' }
]

const onScroll = () => {
  scrolled.value = window.scrollY > 20
}

onMounted(() => {
  window.addEventListener('scroll', onScroll)
})

onUnmounted(() => {
  window.removeEventListener('scroll', onScroll)
})
</script>

// src/components/Navbar.tsx
"use client";

import { useState, useEffect } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Menu, X, Shield } from "lucide-react";

const navLinks = [
  { label: "Solution", href: "#solution" },
  { label: "Fonctionnalités", href: "#features" },
  { label: "Pourquoi nous", href: "#values" },
  { label: "Tarifs", href: "#pricing" },
];

export default function Navbar() {
  const [isOpen, setIsOpen] = useState(false);
  const [scrolled, setScrolled] = useState(false);

  useEffect(() => {
    const onScroll = () => setScrolled(window.scrollY > 20);
    window.addEventListener("scroll", onScroll);
    return () => window.removeEventListener("scroll", onScroll);
  }, []);

  return (
    <motion.nav
      initial={{ y: -100 }}
      animate={{ y: 0 }}
      transition={{ duration: 0.6, ease: "easeOut" }}
      className={`fixed top-0 left-0 right-0 z-50 transition-all duration-500 ${
        scrolled
          ? "glass shadow-lg shadow-navy/5"
          : "bg-transparent"
      }`}
    >
      <div className="max-w-7xl mx-auto px-6 lg:px-8">
        <div className="flex items-center justify-between h-16 lg:h-20">
          {/* Logo */}
          <a href="#" className="flex items-center gap-2 group">
            <div className="relative">
              <div className="w-9 h-9 rounded-xl bg-gradient-to-br from-teal to-green flex items-center justify-center group-hover:shadow-lg group-hover:shadow-teal/30 transition-shadow duration-300">
                <Shield className="w-5 h-5 text-white" strokeWidth={2.5} />
              </div>
              <div className="absolute -top-0.5 -right-0.5 w-3 h-3 bg-orange rounded-full animate-pulse-soft" />
            </div>
            <span className="text-xl font-bold text-navy">
              Safe<span className="text-teal">Nest</span>
            </span>
          </a>

          {/* Desktop links */}
          <div className="hidden md:flex items-center gap-8">
            {navLinks.map((link) => (
              <a
                key={link.href}
                href={link.href}
                className="text-sm font-medium text-navy/80 hover:text-navy transition-colors duration-200 relative group"
              >
                {link.label}
                <span className="absolute -bottom-1 left-0 w-0 h-0.5 bg-gradient-to-r from-teal to-green group-hover:w-full transition-all duration-300" />
              </a>
            ))}
            <a
              href="#pricing"
              className="ml-2 px-5 py-2.5 rounded-full bg-navy text-white text-sm font-semibold hover:bg-navy-600 transition-all duration-300 hover:shadow-lg hover:shadow-navy/20 hover:-translate-y-0.5"
            >
              Commencer
            </a>
          </div>

          {/* Mobile toggle */}
          <button
            onClick={() => setIsOpen(!isOpen)}
            className="md:hidden p-2 rounded-lg hover:bg-navy/5 transition-colors"
          >
            {isOpen ? (
              <X className="w-6 h-6 text-navy" />
            ) : (
              <Menu className="w-6 h-6 text-navy" />
            )}
          </button>
        </div>
      </div>

      {/* Mobile menu */}
      <AnimatePresence>
        {isOpen && (
          <motion.div
            initial={{ opacity: 0, height: 0 }}
            animate={{ opacity: 1, height: "auto" }}
            exit={{ opacity: 0, height: 0 }}
            transition={{ duration: 0.3 }}
            className="md:hidden glass border-t border-white/20"
          >
            <div className="px-6 py-4 space-y-3">
              {navLinks.map((link) => (
                <a
                  key={link.href}
                  href={link.href}
                  onClick={() => setIsOpen(false)}
                  className="block text-sm font-medium text-navy/70 hover:text-navy py-2"
                >
                  {link.label}
                </a>
              ))}
              <a
                href="#pricing"
                onClick={() => setIsOpen(false)}
                className="block text-center mt-2 px-5 py-2.5 rounded-full bg-navy text-white text-sm font-semibold"
              >
                Commencer
              </a>
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </motion.nav>
  );
}
